pipeline {

    agent any

    environment {
        DOCKER_IMAGE = 'kusumlohar03/thymeleaf-practice:latest'
        CONTAINER_NAME = 'thymeleaf-practice'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('thymeleafpractice') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('thymeleafpractice') {
                    sh 'docker build -t $DOCKER_IMAGE .'
                }
            }
        }

        stage('Docker Push') {
    steps {
        withCredentials([
            usernamePassword(
                credentialsId: 'dockerhub',
                usernameVariable: 'DOCKER_USERNAME',
                passwordVariable: 'DOCKER_PASSWORD'
            )
        ]) {
            sh '''
                echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
                docker push $DOCKER_IMAGE
                docker logout
            '''
        }
    }
}

        stage('Deploy') {
            steps {
                sh '''
                    docker pull $DOCKER_IMAGE

                    docker stop $CONTAINER_NAME || true
                    docker rm $CONTAINER_NAME || true

                    docker run -d \
                        -p 8082:8080 \
                        --name $CONTAINER_NAME \
                        $DOCKER_IMAGE
                '''
            }
        }
    }
}
